version: "3.3"
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    container_name: database
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/data/database:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  app:
    build: ./
    restart: always
    container_name: league-test
    environment:
      - APPLICATION_NAME=league-test
      - APPLICATION_DESCRIPTION=League test task api
      - VERSION=1.0
      - NODE_ENV=development
      - IP=127.0.0.1
      - PORT=8080
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8080:8080